# .github/workflows/publish.yml
name: Publish python package
on: push
jobs:
  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/interface-gen
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install twine
      working-directory: .
      run: pip install twine
    - name: Build package distributions
      working-directory: .
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
